/**
 * Sync OpenClaw `mcp.servers` into AO MCP provider YAML fragments.
 * AO then launches those MCP servers itself (stdio / streamable-http).
 */
import * as fs from "node:fs";
import * as path from "node:path";

type Logger = {
  info: (m: string) => void;
  warn?: (m: string) => void;
  error?: (m: string) => void;
};

export const OPENCLAW_MCP_CATALOG_DIRNAME = "openclaw-mcp-providers";
const MANAGED_PREFIX = "openclaw_";

function asRecord(v: unknown): Record<string, unknown> | undefined {
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : undefined;
}

function plainString(v: unknown): string | undefined {
  if (typeof v === "string" && v.trim()) return v.trim();
  const obj = asRecord(v);
  if (!obj) return undefined;
  if (typeof obj.value === "string" && obj.value.trim()) return obj.value.trim();
  return undefined;
}

function stringMap(raw: unknown): Record<string, string> | undefined {
  const obj = asRecord(raw);
  if (!obj) return undefined;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(obj)) {
    const key = String(k).trim();
    const val = plainString(v);
    if (!key || val === undefined) continue;
    out[key] = val;
  }
  return Object.keys(out).length ? out : undefined;
}

/** AO-safe id: openclaw_<sanitized_openclaw_name> */
export function openClawMcpProviderId(serverName: string): string {
  const cleaned = String(serverName)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
  const base = cleaned || "server";
  const withPrefix = base.startsWith(MANAGED_PREFIX) ? base : `${MANAGED_PREFIX}${base}`;
  // AO ids should start with a letter
  return /^[a-z]/.test(withPrefix) ? withPrefix : `m_${withPrefix}`;
}

export function pathListSep(): string {
  return process.platform === "win32" ? ";" : ":";
}

export function mergeExtraMcpProvidersPath(existing: string | undefined, catalogDir: string): string {
  const sep = pathListSep();
  const parts = (existing || "")
    .split(sep)
    .map((p) => p.trim())
    .filter(Boolean);
  const abs = path.resolve(catalogDir);
  const filtered = parts.filter((p) => path.resolve(p) !== abs);
  return [abs, ...filtered].join(sep);
}

/** Richer planner keywords for common OpenClaw MCP server names. */
function filesystemGoalKeywords(openClawName: string, id: string): string[] {
  const base = [
    `  - ${yamlScalar(openClawName)}`,
    `  - "openclaw mcp"`,
    `  - ${yamlScalar(id)}`,
  ];
  if (openClawName.trim().toLowerCase() !== "filesystem") return base;
  return [
    ...base,
    `  - "list files"`,
    `  - "list directory"`,
    `  - "workspace"`,
    `  - "read file"`,
    `  - "absolute path"`,
    `  - "filesystem tools"`,
  ];
}

function yamlScalar(value: string): string {
  // Prefer JSON string quoting — always valid YAML.
  return JSON.stringify(value);
}

function yamlStringMap(indent: string, map: Record<string, string>): string[] {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(map)) {
    lines.push(`${indent}${JSON.stringify(k)}: ${yamlScalar(v)}`);
  }
  return lines;
}

export type MappedOpenClawMcp =
  | {
      ok: true;
      id: string;
      openClawName: string;
      yaml: string;
      kind: "stdio" | "streamable_http";
    }
  | {
      ok: false;
      openClawName: string;
      reason: string;
    };

export function mapOpenClawMcpServer(serverName: string, raw: unknown): MappedOpenClawMcp {
  const name = String(serverName).trim();
  if (!name) {
    return { ok: false, openClawName: String(serverName), reason: "empty server name" };
  }

  const entry = asRecord(raw);
  if (!entry) {
    return { ok: false, openClawName: name, reason: "server entry must be an object" };
  }

  if (entry.enabled === false) {
    return { ok: false, openClawName: name, reason: "disabled (enabled: false)" };
  }

  const id = openClawMcpProviderId(name);
  const auth = plainString(entry.auth)?.toLowerCase();
  if (auth === "oauth") {
    return {
      ok: false,
      openClawName: name,
      reason: "OAuth MCP servers are not synced (AO cannot use OpenClaw OAuth token store yet)",
    };
  }

  const command = plainString(entry.command);
  const url = plainString(entry.url);
  const transport = (plainString(entry.transport) || plainString(entry.type) || "").toLowerCase();

  const description =
    plainString(entry.description) ||
    `OpenClaw MCP server "${name}" (synced from mcp.servers). AO launches this server itself.`;
  const capabilities =
    plainString(entry.capabilities) ||
    "Tools and resources advertised by this MCP server when connected.";
  const plannerHint =
    plainString(entry.planner_hint) ||
    plainString(entry.plannerHint) ||
    `Use when the user request matches capabilities of OpenClaw MCP server "${name}".`;

  const headerLines = [
    `# Auto-generated by @zlatko-lakisic/openclaw-agentic-orchestration`,
    `# Source: OpenClaw mcp.servers[${JSON.stringify(name)}]`,
    `# Do not edit — overwritten on gateway start.`,
    `id: ${id}`,
    `description: >-`,
    `  ${description.replace(/\s+/g, " ").trim()}`,
    `capabilities: >-`,
    `  ${capabilities.replace(/\s+/g, " ").trim()}`,
    `good_for: >-`,
    `  Tasks that OpenClaw operators configured this MCP server to handle.`,
    `planner_hint: >-`,
    `  ${plannerHint.replace(/\s+/g, " ").trim()}`,
    `user_goal_keywords:`,
    ...filesystemGoalKeywords(name, id),
  ];

  if (command) {
    const argsRaw = entry.args;
    const args = Array.isArray(argsRaw)
      ? argsRaw.map((a) => plainString(a) ?? String(a))
      : [];
    const env = stringMap(entry.env);
    if (entry.cwd != null && plainString(entry.cwd)) {
      // AO stdio resolver has no cwd field yet — surface via env when possible.
      // Operators with cwd-sensitive servers should prefer absolute command paths.
    }

    const lines = [...headerLines, `stdio:`, `  command: ${yamlScalar(command)}`];
    if (args.length > 0) {
      lines.push(`  args:`);
      for (const a of args) lines.push(`    - ${yamlScalar(a)}`);
    }
    if (env) {
      lines.push(`  env:`);
      lines.push(...yamlStringMap("    ", env));
    }
    lines.push("");
    return { ok: true, id, openClawName: name, kind: "stdio", yaml: lines.join("\n") };
  }

  if (url) {
    if (transport === "sse") {
      return {
        ok: false,
        openClawName: name,
        reason: "transport sse is not supported by AO (use streamable-http)",
      };
    }
    // Default remote / type:http / streamable-http
    const headers = stringMap(entry.headers);
    const lines = [
      ...headerLines,
      `streamable_http:`,
      `  url: ${yamlScalar(url)}`,
    ];
    if (headers) {
      lines.push(`  headers:`);
      lines.push(...yamlStringMap("    ", headers));
    }
    lines.push("");
    return {
      ok: true,
      id,
      openClawName: name,
      kind: "streamable_http",
      yaml: lines.join("\n"),
    };
  }

  return {
    ok: false,
    openClawName: name,
    reason: "need stdio command or remote url",
  };
}

export function extractOpenClawMcpServers(
  openClawConfig: Record<string, unknown> | undefined,
): Record<string, unknown> {
  const mcp = asRecord(openClawConfig?.mcp);
  const servers = asRecord(mcp?.servers);
  return servers ?? {};
}

export interface SyncOpenClawMcpResult {
  catalogDir: string;
  written: string[];
  skipped: Array<{ name: string; reason: string }>;
}

/**
 * Write AO MCP fragments for every usable OpenClaw mcp.servers entry.
 * Removes previously generated `openclaw_*.yaml` files in the catalog dir.
 */
export function syncOpenClawMcpProviders(params: {
  dataRoot: string;
  openClawConfig?: Record<string, unknown>;
  logger?: Logger;
}): SyncOpenClawMcpResult {
  const catalogDir = path.join(params.dataRoot, OPENCLAW_MCP_CATALOG_DIRNAME);
  fs.mkdirSync(catalogDir, { recursive: true });

  // Drop prior managed fragments so deleted OpenClaw servers disappear.
  for (const name of fs.readdirSync(catalogDir)) {
    if (!name.endsWith(".yaml") && !name.endsWith(".yml")) continue;
    if (!name.startsWith(MANAGED_PREFIX) && !name.startsWith("m_openclaw_")) continue;
    // Keep the plugin-hosted tool bridge fragment (rewritten separately).
    if (name === "openclaw_bridge.yaml" || name === "openclaw_bridge.yml") continue;
    try {
      fs.unlinkSync(path.join(catalogDir, name));
    } catch {
      /* ignore */
    }
  }

  const servers = extractOpenClawMcpServers(params.openClawConfig);
  const written: string[] = [];
  const skipped: Array<{ name: string; reason: string }> = [];

  for (const [name, raw] of Object.entries(servers)) {
    const mapped = mapOpenClawMcpServer(name, raw);
    if (!mapped.ok) {
      skipped.push({ name: mapped.openClawName, reason: mapped.reason });
      continue;
    }
    const filePath = path.join(catalogDir, `${mapped.id}.yaml`);
    fs.writeFileSync(filePath, mapped.yaml, { mode: 0o600 });
    written.push(mapped.id);
  }

  if (written.length || skipped.length) {
    params.logger?.info?.(
      `[agentic-orchestration] Synced OpenClaw MCP → AO catalog ${catalogDir} ` +
        `(${written.length} written, ${skipped.length} skipped)`,
    );
  } else {
    params.logger?.info?.(
      `[agentic-orchestration] No OpenClaw mcp.servers entries to sync (${catalogDir})`,
    );
  }
  for (const s of skipped) {
    params.logger?.warn?.(
      `[agentic-orchestration] Skipped OpenClaw MCP ${JSON.stringify(s.name)}: ${s.reason}`,
    );
  }

  return { catalogDir, written, skipped };
}
